### ISSUE TITLE
Bundle up txt files

### ISSUE THREAD

**Issue by stvnrlly** [DCgov/poirot-patterns#5]
In the event that somebody just wants to cover all of the bases, an `all.txt` file would be useful.

**Comment by emanuelfeld** [comment]
This would be for running it manually from the command line, rather than as a commit hook? I advocated that people clone this to their computer and use the folder in the commit hook. Makes things easier if you want to modify the patterns used, since it avoids issues with git init. Though I imagine https://github.com/DCgov/poirot/issues/31 would also help with that.

**Comment by stvnrlly** [comment]
My use case so far is the hook, but I think it applies to the main CLI interface as well. The reasoning is that I'm imagining the hook running on all of an organization's repos, across many users and projects. In that scenario, it's not likely that each user will keep multiple local pattern files up to date, so it would be more reliable to be able to point to one canonical URL that does it all.

Of course, if a user wants to modify the patterns, they can dig in and do it easily, but I think this would be a sensible default. And if you want to avoid the bundling, I can always bundle my own, so no worries there.

**Comment by emanuelfeld** [comment]
Those other files were broken out from the other because, in most cases they produce too many false positives (most are just long strings of numbers). Perhaps you've already done this, but I'll propose that you test out the various pattern files on some repo of yours to see what each brings up (do a --revlist="all").

**Comment by stvnrlly** [comment]
Gotcha. I'll use it some more and see how it goes. Feel free to close this issue in the meantime, since it sounds like you've already thought this through.
